services:
  stock-visual:
    build: .
    container_name: stock-visual
    ports:
      - "127.0.0.1:8888:8888"
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./.cache:/app/.cache
      - ./data:/app/data
    restart: unless-stopped
